global:
  resolve_timeout: 5m
route:
  receiver: telegram_receiver
receivers:
  - name: telegram_receiver
    telegram_configs:
    - bot_token: YOUR_BOT_TOKEN
      api_url: https://api.telegram.org
      chat_id: YOUR_CHAT_ID
      message: '{{ template "telegram.alert_msg.message" . }}'

templates:
  - '/etc/alertmanager/templates/alert_msg.tmpl'