groups:
  - name: node_exporter_alerts
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Host high CPU load
        description: CPU load is > 80% VALUE = {{ $value }}
    - alert: HostOutOfMemory
      expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 20
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Host out of memory
        description: Node memory is filling up (< 20% left) VALUE = {{ $value }}
    - alert: HostOutOfDiskSpace
      expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 20
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: Host out of disk space
        description: Disk is almost full (< 20% left) VALUE = {{ $value }}
  - name: cadvisor_alerts
    rules:
      - alert: ContainerExited
        expr: time() - container_last_seen > 60
        for: 10s
        labels:
          severity: error
        annotations:
          summary: Container is not visible for a long time
          description: Container was last seen {{ $value }} seconds ago
